CREATE FUNCTION UPD() RETURNS TRIGGER
	language 'plpgsql'
	as
	$$ 
	begin
		UPDATE SUMMARY
		SET ITEMS = ITEMS + NEW.QUANTITY;
    	UPDATE SUMMARY
		SET TOTAL_PRICE = TOTAL_PRICE + NEW.ITEM_PRICE*NEW.QUANTITY;
		RETURN NEW;
	end;
	$$;

CREATE FUNCTION DEL() RETURNS TRIGGER
	language 'plpgsql'
	as
	$$
	begin 
	UPDATE SUMMARY
	SET ITEMS = ITEMS - OLD.QUANTITY;
    UPDATE SUMMARY
	SET TOTAL_PRICE = TOTAL_PRICE - OLD.ITEM_PRICE*OLD.QUANTITY;
	RETURN OLD;
	end;
	$$;

CREATE TRIGGER UPDATE 
	AFTER INSERT 
	ON ORDER_ITEM 
	FOR EACH ROW 
	EXECUTE PROCEDURE UPD();

CREATE TRIGGER DELETE
	AFTER DELETE
	ON ORDER_ITEM
	FOR EACH ROW 
	EXECUTE PROCEDURE DEL();	

SELECT * FROM ORDER_ITEM;
SELECT * FROM SUMMARY;

INSERT INTO ORDER_ITEM values('Stickers' , 100 , 5);

SELECT * FROM ORDER_ITEM;
SELECT * FROM SUMMARY;

